---
apiVersion: v1
kind: Service
metadata:
  name: otelcol
  namespace: telemetry
spec:
  ports:
    - name: grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: prometheus
      port: 8889
      protocol: TCP
      targetPort: 8889
  selector:
    k8s-app: otelcol
